{% set version = "1.3" %}

package:
  name: iapws
  version: {{version}}

source:
  url: https://pypi.io/packages/sourcei/iapws/iapws-{{ version }}.tar.gz
  sha256: 5ca65ea896eefc46ceaaf6628554633eeeeecef6a99c1a62284edae46d6430aa

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - scipy
  run:
    - python
    - scipy

test:
  imports:
    - iapws

about:
  home: https://github.com/jjgomera/iapws
  license: GPL-3.0
  summary: 'Python implementation of standards from The InternationalAssociation for the Properties of Water and Steam'
  license_family: GPL3

extra:
  recipe-maintainers:
    - tntmatthews
