travis:
  secure:
    BINSTAR_TOKEN: m5b2zL2SBu92giugdB4OrGdZ14JSz8oz8v5/p/8wLdXrCmkxg65UKPs9KIYJKkFLH2Av74ycYmYpcFaoMpULtiy8vOEMCcX8LmIzW45MvX3yllPLgOLcUsVFR1VKiqXsKhpbSOuog1+SaCBZrwZi0RESTy3AASLACd81QvOJ3K8XL0X2QDh/t3lhWE7MnKlUUGCFLydOlPBnUyPwjk90p0PH3vqQzZ9UnalKAAFDuesAXyRxJWctb0n1XYmPY5Ff5iAK08chXfLpPOIVxAdLmkZwcFRyyE3/z8P9U3FYegsLxoL2kAczFj2yY49fjMLNnzMSzhH+3Df2spawGPHPYNs5r85AaEtfCgAMLnFiwO5OdSA32fwRx3OD7vN5dhnmTjUKp64tURJmc7/uG3XT1PM5eIIImYFI6Enu5SI4CRNQpqcjk0wAhCj4mI7EBxat3LhbTzrvgfzBdjUDtWP8dmC2VlGaoy0m5I6zE9wQchoTVJhHGyB8CkMBh2G0Z5oesXYQXxDoF4zBCZjkearXmxV82GCLVHvmbck2HBBUm+uLPk12iaH6T4PNN0hOnxhw+G7VV28WwIj3zZqADe6Od+IMIq5yVdw1qOqoFLm6vP+llyosUUJN45NHwRJVv1VE/D4QPYaydI6/l/SFSo0xkB3cVXGue1Nx2H0tfVsRYkI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
